package com.luisfagundes.movies.presentation.categories

import com.luisfagundes.domain.enum.MovieCategoryType
import com.luisfagundes.movies.presentation.baseCategory.BaseMovieCategoryFragment

class MoviesReleasedThisYearFragment : BaseMovieCategoryFragment(MovieCategoryType.RELEASED_THIS_YEAR)