package com.luisfagundes.movies.presentation.categories

import com.luisfagundes.domain.enum.MovieCategoryType
import com.luisfagundes.movies.presentation.baseCategory.BaseMovieCategoryFragment

class UpcomingMoviesFragment : BaseMovieCategoryFragment(MovieCategoryType.UPCOMING)